"""Markdown renderer for ``owlcompare diff`` — PR-comment ready (Component 15).

Produces a severity-sectioned Markdown document suitable for a GitHub PR comment,
a committed file, or any Markdown viewer. The layout is fixed (sections omitted
when empty): an at-a-glance title, a "Compared A against B" line, a Renames
section, a Breaking-changes section, an Other-changes section, a collapsed
``<details>`` block for unexplained Layer 0 triples, and a footer. See
``specs/15-markdown-report.md`` for the contract and the per-kind templates.
"""

from __future__ import annotations

from dataclasses import dataclass

from owlcompare._version import __version__
from owlcompare.diff._common import Change, DiffResult, Severity, shorten_synthetic_iri

from ._markdown_helpers import (
    escape_markdown,
    normalize_source,
    prefix_iri,
    rename_icon,
    severity_icon,
    title_icon,
)

# Human-facing noun per entity kind, used by entity add/remove and rename
# templates. Mirrors the producer-side nouns in the diff slices.
_KIND_NOUN: dict[str, str] = {
    "class": "Class",
    "object_property": "Object property",
    "data_property": "Data property",
    "annotation_property": "Annotation property",
    "individual": "Individual",
    "datatype": "Datatype",
}

_OTHER_SEVERITIES: tuple[Severity, ...] = ("non_breaking", "additive", "info")


@dataclass(frozen=True, slots=True)
class MarkdownOptions:
    """Configuration for Markdown rendering."""

    include_footer: bool = True  # The "Generated by owlcompare" attribution
    include_layer0_collapsed: bool = True  # The <details> block for unsubsumed Layer 0
    max_changes_per_section: int = 50  # Truncate long sections with "...and N more"
    emoji_style: str = "github"  # 'github' for 🔴🟡🟢⚪ ✏️; 'plain' for [BREAKING], [WARN], etc.
    heading_level: int = 2  # Top heading level (h2 by default; CI may want h3)


def render(
    result: DiffResult,
    options: MarkdownOptions | None = None,
) -> str:
    """Render a ``DiffResult`` as Markdown.

    Returns the full Markdown document as a string with no leading or trailing
    whitespace (the caller appends a trailing newline when writing). The caller
    decides where the output goes — stdout, a file, or an HTTP API.
    """
    options = options or MarkdownOptions()
    emoji = options.emoji_style != "plain"
    heading = options.heading_level if 1 <= options.heading_level <= 4 else 2
    prefixes = {**result.a.prefixes, **result.b.prefixes}

    changes = list(result.changes)
    registry = result.metadata.get("subsumption_registry")

    structural = [c for c in changes if c.layer == "structural"]
    layer0 = [c for c in changes if c.layer == "syntactic"]
    unexplained = [c for c in layer0 if not _is_explained(registry, c)]

    renames = [c for c in structural if c.kind.endswith("_renamed")]
    non_rename = [c for c in structural if not c.kind.endswith("_renamed")]
    breaking = [c for c in non_rename if c.severity == "breaking"]
    other = [c for c in non_rename if c.severity in _OTHER_SEVERITIES]

    breaking_total = len(breaking) + sum(1 for c in unexplained if c.severity == "breaking")

    blocks: list[str] = [
        _title(heading, breaking_total, len(changes), emoji=emoji),
        _compared_line(result),
    ]
    if renames:
        blocks.append(_change_section("Renames", renames, prefixes, options, emoji=emoji))
    if breaking:
        blocks.append(_change_section("Breaking changes", breaking, prefixes, options, emoji=emoji))
    if other:
        blocks.append(_change_section("Other changes", other, prefixes, options, emoji=emoji))
    if unexplained and options.include_layer0_collapsed:
        blocks.append(_layer0_collapsed(unexplained, options, emoji=emoji))
    if options.include_footer:
        blocks.append(_footer())

    return "\n\n".join(blocks)


# --------------------------------------------------------------------------- #
# Title + header
# --------------------------------------------------------------------------- #


def _title(heading: int, breaking_total: int, total: int, *, emoji: bool) -> str:
    """The h2 (configurable) status line: icon + ``owlcompare diff: <phrase>``."""
    if breaking_total > 0:
        status, phrase = "breaking", _pluralize(breaking_total, "breaking change")
    elif total > 0:
        status, phrase = "ok", "no breaking changes"
    else:
        status, phrase = "none", "no changes"
    icon = title_icon(status, emoji=emoji)
    return f"{'#' * heading} {icon} owlcompare diff: {phrase}"


def _compared_line(result: DiffResult) -> str:
    """The ``Compared `A` against `B`.`` line (sources, or a placeholder)."""
    source_a = normalize_source(result.a.source) if result.a.source else "ontology A"
    source_b = normalize_source(result.b.source) if result.b.source else "ontology B"
    return f"Compared `{source_a}` against `{source_b}`."


def _pluralize(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"


# --------------------------------------------------------------------------- #
# Sections
# --------------------------------------------------------------------------- #


def _change_section(
    title: str,
    items: list[Change],
    prefixes: dict[str, str],
    options: MarkdownOptions,
    *,
    emoji: bool,
) -> str:
    """A ``### Title (N)`` heading followed by a (possibly truncated) bullet list."""
    bullets: list[str] = []
    for change in items[: options.max_changes_per_section]:
        if change.kind.endswith("_renamed"):
            icon = rename_icon(emoji=emoji)
        else:
            icon = severity_icon(change.severity, emoji=emoji)
        bullets.append(f"- {icon} {_format_change(change, prefixes)}")
    _append_truncation(bullets, len(items), options.max_changes_per_section)
    return f"### {title} ({len(items)})\n\n" + "\n".join(bullets)


def _layer0_collapsed(items: list[Change], options: MarkdownOptions, *, emoji: bool) -> str:
    """The collapsible ``<details>`` block of unexplained Layer 0 triple changes.

    Raw HTML is permitted here (spec Q2): GitHub renders it natively, and other
    renderers degrade to showing the content as plain text.
    """
    bullets: list[str] = []
    for change in items[: options.max_changes_per_section]:
        icon = severity_icon(change.severity, emoji=emoji)
        bullets.append(f"- {icon} {_format_layer0(change)}")
    _append_truncation(bullets, len(items), options.max_changes_per_section)
    summary_prefix = "📜 " if emoji else ""
    body = "\n".join(bullets)
    return (
        "<details>\n"
        f"<summary>{summary_prefix}{len(items)} unexplained Layer 0 changes</summary>\n\n"
        f"{body}\n"
        "</details>"
    )


def _append_truncation(bullets: list[str], total: int, limit: int) -> None:
    """Append the ``...and N more`` marker when a section overflows ``limit``."""
    if total > limit:
        bullets.append(f"- ...and {total - limit} more (see JSON output for full list)")


def _footer() -> str:
    """The attribution footer (Q3: JSON pointer is plain text, not a link)."""
    return (
        "---\n"
        f"*Generated by owlcompare {__version__} · "
        "[Schema](docs/schema/diff-result.schema.json) · "
        "Run with --format json for machine-readable output*"
    )


# --------------------------------------------------------------------------- #
# Per-kind change formatting
# --------------------------------------------------------------------------- #


def _format_change(change: Change, prefixes: dict[str, str]) -> str:
    """Return the Markdown bullet *body* (no leading ``-`` or icon) for a change.

    Each well-known kind has a precise template (spec § Per-kind summary
    formatting). Unknown kinds fall back to the producer's ``summary``.
    """
    handler = _entity_addremove(change.kind)
    if handler is not None:
        return _format_entity(change, prefixes, *handler)
    if change.kind.endswith("_renamed"):
        return _format_rename(change, prefixes)

    formatter = _KIND_FORMATTERS.get(change.kind)
    if formatter is not None:
        return formatter(change, prefixes)
    return change.summary


def _entity_addremove(kind: str) -> tuple[str, str] | None:
    """Split ``class_added`` → ``('class', 'added')`` for entity kinds, else ``None``."""
    for action in ("added", "removed"):
        suffix = f"_{action}"
        if kind.endswith(suffix):
            entity_kind = kind[: -len(suffix)]
            if entity_kind in _KIND_NOUN:
                return entity_kind, action
    return None


def _format_entity(change: Change, prefixes: dict[str, str], entity_kind: str, action: str) -> str:
    """``**Class added:** `era:Platform` *"Platform"@en*`` and its kin."""
    noun = _KIND_NOUN[entity_kind]
    iri = _code(prefix_iri(_str(change.details.get("entity_iri")), prefixes))
    body = f"**{noun} {action}:** {iri}"
    return body + _label_suffix(change.details.get("label"), change.details.get("language"))


def _format_rename(change: Change, prefixes: dict[str, str]) -> str:
    """``**Class renamed:** `era:Track` → `era:RailwayTrack` *(high confidence — ...)*``."""
    details = change.details
    noun = _KIND_NOUN.get(_str(details.get("entity_kind")), "Entity")
    before = _code(prefix_iri(_str(details.get("before_iri")), prefixes))
    after = _code(prefix_iri(_str(details.get("after_iri")), prefixes))
    confidence = _str(details.get("confidence"))
    conf_text = confidence if confidence == "certain" else f"{confidence} confidence"
    evidence = [escape_markdown(str(e)) for e in details.get("evidence", [])]
    summary = f"{conf_text} — {'; '.join(evidence)}" if evidence else conf_text
    return f"**{noun} renamed:** {before} → {after} *({summary})*"


def _format_parent_added(change: Change, prefixes: dict[str, str]) -> str:
    child = _code(prefix_iri(_str(change.details.get("entity_iri")), prefixes))
    parent = _code(prefix_iri(_str(change.details.get("parent_iri")), prefixes))
    return f"**Class parent added:** {child} gained {parent}"


def _format_parent_removed(change: Change, prefixes: dict[str, str]) -> str:
    child = _code(prefix_iri(_str(change.details.get("entity_iri")), prefixes))
    parent = _code(prefix_iri(_str(change.details.get("parent_iri")), prefixes))
    return f"**Class parent removed:** {child} lost {parent}"


def _format_reparented(change: Change, prefixes: dict[str, str]) -> str:
    child = _code(prefix_iri(_str(change.details.get("entity_iri")), prefixes))
    old = _parent_set(change.details.get("parents_before"), prefixes)
    new = _parent_set(change.details.get("parents_after"), prefixes)
    direction = _str(change.details.get("direction"))
    return f"**Class reparented:** {child}: {old} → {new} ({direction})"


def _format_restriction_added(change: Change, prefixes: dict[str, str]) -> str:
    return _restriction(change, prefixes, "**Restriction added on**")


def _format_restriction_removed(change: Change, prefixes: dict[str, str]) -> str:
    return _restriction(change, prefixes, "**Restriction removed from**")


def _format_restriction_changed(change: Change, prefixes: dict[str, str]) -> str:
    return _restriction(change, prefixes, "**Restriction changed on**")


def _restriction(change: Change, prefixes: dict[str, str], prefix: str) -> str:
    """Shared restriction template: prefix + entity + the producer's readable form.

    The readable form (``era:hasMaxSpeed max 1 → max 2`` etc.) is reused verbatim
    from the producer's ``summary`` — the diff slice already rendered it with the
    same shortening rules — so we only re-bold the prefix and re-code the entity.
    """
    entity = _code(prefix_iri(_str(change.details.get("entity_iri")), prefixes))
    return f"{prefix} {entity}: {_code(_readable_form(change))}"


def _format_domain_changed(change: Change, prefixes: dict[str, str]) -> str:
    return _domain_range(change, prefixes, "Domain")


def _format_range_changed(change: Change, prefixes: dict[str, str]) -> str:
    return _domain_range(change, prefixes, "Range")


def _domain_range(change: Change, prefixes: dict[str, str], noun: str) -> str:
    prop = _code(prefix_iri(_str(change.details.get("property_iri")), prefixes))
    before = prefix_iri(_str(change.details.get("before")), prefixes)
    after = prefix_iri(_str(change.details.get("after")), prefixes)
    return f"**{noun} changed on** {prop}: {before} → {after}"


def _format_equivalent_added(change: Change, prefixes: dict[str, str]) -> str:
    entity = _code(prefix_iri(_str(change.details.get("entity_iri")), prefixes))
    other = _code(prefix_iri(_str(change.details.get("other_iri")), prefixes))
    return f"**Equivalent class added:** {entity} ≡ {other}"


def _format_disjoint_added(change: Change, prefixes: dict[str, str]) -> str:
    entity = _code(prefix_iri(_str(change.details.get("entity_iri")), prefixes))
    other = _code(prefix_iri(_str(change.details.get("other_iri")), prefixes))
    return f"**Disjoint with added:** {entity} ⊥ {other}"


def _format_deprecated(change: Change, prefixes: dict[str, str]) -> str:
    entity = _code(prefix_iri(_str(change.details.get("entity_iri")), prefixes))
    return f"**Deprecated:** {entity}"


def _format_annotation_changed(change: Change, prefixes: dict[str, str]) -> str:
    details = change.details
    entity = _code(prefix_iri(_str(details.get("entity_iri")), prefixes))
    is_comment = _str(details.get("predicate_short")) == "comment"
    noun = "Comment changed" if is_comment else "Label changed"
    language = details.get("language")
    lang_part = f" ({language})" if language else ""
    before = escape_markdown(_annotation_value(details.get("before")))
    after = escape_markdown(_annotation_value(details.get("after")))
    return f'**{noun}** on {entity}{lang_part}: *"{before}"* → *"{after}"*'


def _format_ontology_metadata_changed(change: Change, prefixes: dict[str, str]) -> str:
    details = change.details
    predicate = _code(prefix_iri(_str(details.get("predicate_iri")), prefixes))
    before = escape_markdown(_annotation_value(details.get("before")))
    after = escape_markdown(_annotation_value(details.get("after")))
    return f'**Ontology metadata:** {predicate} *"{before}"* → *"{after}"*'


def _format_summary_lead(change: Change, prefixes: dict[str, str]) -> str:
    """Bold the lead clause of the producer summary; keep the readable tail verbatim.

    The Component 12.5 slices already render their summaries with the same prefix /
    synthetic-URN shortening the renderer uses (``Domain expanded on era:X: + era:Y``,
    ``Range facet changed on era:Z: max 327670 → 100000`` …), so the template only
    re-bolds the lead before the first ``": "`` rather than re-deriving the phrase.
    """
    del prefixes  # the producer already shortened the IRIs in the summary
    summary = " ".join(shorten_synthetic_iri(token) for token in change.summary.split(" "))
    lead, sep, tail = summary.partition(": ")
    if sep:
        return f"**{lead}:** {tail}"
    return f"**{summary}**"


# Dispatch table for kinds whose template does not follow the entity-add/remove
# or rename pattern. Kinds absent here (and not entity/rename) fall back to the
# producer ``summary`` — the spec's forward-compatible default.
_KIND_FORMATTERS = {
    "class_parent_added": _format_parent_added,
    "class_parent_removed": _format_parent_removed,
    "class_reparented": _format_reparented,
    "restriction_added": _format_restriction_added,
    "restriction_removed": _format_restriction_removed,
    "restriction_changed": _format_restriction_changed,
    "domain_changed": _format_domain_changed,
    "range_changed": _format_range_changed,
    "equivalent_class_added": _format_equivalent_added,
    "disjoint_added": _format_disjoint_added,
    "entity_deprecated": _format_deprecated,
    "annotation_changed": _format_annotation_changed,
    "ontology_metadata_changed": _format_ontology_metadata_changed,
    # Component 12.5 — anonymous class sets, datatype facets, isReplacedBy. Each
    # producer summary already follows the spec's pattern; the template re-bolds
    # the lead clause for the PR-comment layout.
    "domain_union_added": _format_summary_lead,
    "domain_union_removed": _format_summary_lead,
    "domain_union_changed": _format_summary_lead,
    "range_union_added": _format_summary_lead,
    "range_union_removed": _format_summary_lead,
    "range_union_changed": _format_summary_lead,
    "subclass_union_added": _format_summary_lead,
    "subclass_union_removed": _format_summary_lead,
    "subclass_union_changed": _format_summary_lead,
    "equivalent_class_union_added": _format_summary_lead,
    "equivalent_class_union_removed": _format_summary_lead,
    "equivalent_class_union_changed": _format_summary_lead,
    "datatype_facet_added": _format_summary_lead,
    "datatype_facet_removed": _format_summary_lead,
    "datatype_facet_changed": _format_summary_lead,
    "datatype_base_changed": _format_summary_lead,
    "replaced_by_set": _format_summary_lead,
    "replaced_by_unset": _format_summary_lead,
}


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #


def _format_layer0(change: Change) -> str:
    """One unexplained Layer 0 bullet: ``Removed: `era:X rdfs:domain era:Y```."""
    summary = " ".join(shorten_synthetic_iri(token) for token in change.summary.split(" "))
    action, _, rest = summary.partition(": ")
    if rest:
        return f"{action}: {_code(rest)}"
    return _code(summary)


def _readable_form(change: Change) -> str:
    """The restriction phrase the producer placed after ``: `` in its summary."""
    _, _, rest = change.summary.partition(": ")
    return rest or change.summary


def _label_suffix(label: object, language: object) -> str:
    """``*"Label"@en*`` suffix, or empty when the change carries no label."""
    if not label:
        return ""
    escaped = escape_markdown(str(label))
    if language:
        return f' *"{escaped}"@{language}*'
    return f' *"{escaped}"*'


def _parent_set(parents: object, prefixes: dict[str, str]) -> str:
    """Comma-joined prefixed parents, or ``(none)`` for an empty set."""
    if not isinstance(parents, list) or not parents:
        return "(none)"
    return ", ".join(prefix_iri(str(p), prefixes) for p in parents)


def _annotation_value(payload: object) -> str:
    """Pull the ``value`` out of an annotation ``before`` / ``after`` payload."""
    if isinstance(payload, dict):
        return str(payload.get("value", ""))
    if payload is None:
        return ""
    return str(payload)


def _is_explained(registry: object, change: Change) -> bool:
    """Whether a Layer 0 change is subsumed by a Layer 1 change (per the registry)."""
    if registry is None:
        return False
    change_id = change.details.get("change_id", "")
    return bool(registry.is_explained(change_id))  # type: ignore[attr-defined]


def _code(text: str) -> str:
    return f"`{text}`"


def _str(value: object) -> str:
    """Coerce an optional ``details`` value to a string (``<unknown>`` for ``None``)."""
    return str(value) if value is not None else "<unknown>"
