"""Acceptance tests for the HTML report — specs/17-html-report.md.

The per-kind summary tests build ``Change`` objects directly and call
:func:`render_change_summary` so each template is pinned in isolation. The
``test_render_golden_*`` tests assert byte-for-byte equality against
``tests/fixtures/html/*.html`` (generated by the renderer, then hand-reviewed);
the timestamp is pinned via ``SOURCE_DATE_EPOCH`` so the goldens are stable.
"""

from __future__ import annotations

import dataclasses
import re
from pathlib import Path

import pytest

from owlcompare.diff import orchestrator
from owlcompare.diff._common import Change, DiffResult
from owlcompare.loader import load
from owlcompare.report._html_components import escape_html, render_change_summary
from owlcompare.report.html_report import HtmlOptions, render

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"
DIFF = FIXTURES / "diff"
RENAME = FIXTURES / "rename"
ANON = FIXTURES / "anonstruct"
GOLDEN = FIXTURES / "html"

_ERA = {"era": "http://data.europa.eu/949/"}


@pytest.fixture(autouse=True)
def _pin_timestamp(monkeypatch: pytest.MonkeyPatch) -> None:
    """Pin SOURCE_DATE_EPOCH so every render in this module is deterministic."""
    monkeypatch.setenv("SOURCE_DATE_EPOCH", "0")


# --------------------------------------------------------------------------- #
# Result / change builders
# --------------------------------------------------------------------------- #


def _result(name_a: str, name_b: str, base: Path = DIFF, **run_kwargs: object) -> DiffResult:
    a = dataclasses.replace(load(str(base / name_a)), source=name_a)
    b = dataclasses.replace(load(str(base / name_b)), source=name_b)
    return orchestrator.run(a, b, **run_kwargs)  # type: ignore[arg-type]


def _render(name_a: str, name_b: str, base: Path = DIFF, **run_kwargs: object) -> str:
    return render(_result(name_a, name_b, base, **run_kwargs))


def _change(kind: str, severity: str = "additive", summary: str = "", **details: object) -> Change:
    return Change(
        layer="structural",
        kind=kind,
        severity=severity,  # type: ignore[arg-type]
        subject=str(details.get("entity_iri") or details.get("before_iri") or ""),
        summary=summary,
        details=details,
    )


def _synthetic_result(count: int) -> DiffResult:
    """A DiffResult with ``count`` additive class_added changes (size/large tests)."""
    snapshot = dataclasses.replace(load(str(DIFF / "html_escaping_before.ttl")), source="a.ttl")
    snapshot_b = dataclasses.replace(snapshot, source="b.ttl")
    changes = tuple(
        Change(
            layer="structural",
            kind="class_added",
            severity="additive",
            subject=f"http://example.org/C{i:05d}",
            summary=f"Class added: ex:C{i:05d}",
            details={
                "entity_iri": f"http://example.org/C{i:05d}",
                "entity_kind": "class",
                "label": f"Class {i:05d}",
                "language": "en",
                "change_id": f"structural:class_added:{i:05d}",
            },
        )
        for i in range(count)
    )
    return DiffResult(a=snapshot, b=snapshot_b, changes=changes, metadata={})


# --------------------------------------------------------------------------- #
# Document skeleton
# --------------------------------------------------------------------------- #


def test_render_returns_valid_html5_document():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert out.startswith("<!DOCTYPE html>")
    assert '<html lang="en"' in out
    assert out.rstrip().endswith("</html>")


def test_render_includes_doctype():
    assert _render("identical_a.ttl", "identical_b.ttl").startswith("<!DOCTYPE html>")


def test_render_includes_charset_utf8():
    assert '<meta charset="UTF-8">' in _render("identical_a.ttl", "identical_b.ttl")


def test_render_includes_viewport_meta():
    out = _render("identical_a.ttl", "identical_b.ttl")
    assert '<meta name="viewport" content="width=device-width, initial-scale=1">' in out


def test_render_inlines_full_css():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert "<style>" in out
    assert "--sev-breaking: #cf222e;" in out  # a token from styles.css
    assert ".change-card {" in out


def test_render_inlines_full_js():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert "owlcompare-theme" in out  # the localStorage key from interactive.js
    assert "addEventListener" in out


def test_render_no_external_resources_loaded():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert "<link" not in out
    assert not re.search(r"<script[^>]*\bsrc\s*=", out)
    assert "<img" not in out


def test_render_html_lang_attribute_set_to_en():
    assert 'lang="en"' in _render("identical_a.ttl", "identical_b.ttl")


# --------------------------------------------------------------------------- #
# Title + status badge
# --------------------------------------------------------------------------- #


def test_render_title_includes_severity_summary():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert "<title>owlcompare diff: 1 breaking change</title>" in out


def test_render_status_badge_breaking_when_breaking_present():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert 'class="status-badge severity-breaking"' in out
    assert "1 breaking change" in out


def test_render_status_badge_green_when_no_breaking():
    out = _render("html_escaping_before.ttl", "html_escaping_after.ttl")
    assert 'class="status-badge severity-additive"' in out
    assert "No breaking changes" in out


def test_render_status_badge_no_changes_when_empty():
    out = _render("identical_a.ttl", "identical_b.ttl")
    assert 'class="status-badge severity-info"' in out
    assert "No changes" in out


def test_render_status_badge_uses_aria_label():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert re.search(r'class="status-badge[^"]*"[^>]*aria-label="[^"]+"', out)


# --------------------------------------------------------------------------- #
# Summary strip
# --------------------------------------------------------------------------- #


def test_render_summary_strip_has_count_for_each_severity():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    for cls in (
        "count-breaking",
        "count-non-breaking",
        "count-additive",
        "count-info",
        "count-renames",
    ):
        assert cls in out


def test_render_summary_strip_omits_zero_counts():
    # Decision: show all five counts always (spec implies show all). Even an empty
    # diff renders every severity bucket so the strip layout is stable.
    out = _render("identical_a.ttl", "identical_b.ttl")
    for cls in (
        "count-breaking",
        "count-non-breaking",
        "count-additive",
        "count-info",
        "count-renames",
    ):
        assert cls in out


# --------------------------------------------------------------------------- #
# Sections
# --------------------------------------------------------------------------- #


def test_render_renames_section_appears_first_when_renames_present():
    out = _render("era_renames_v1.ttl", "era_renames_v2.ttl", base=RENAME)
    main = out[out.index("<main") : out.index("</main>")]
    positions = [
        main.index(f'id="section-{a}"')
        for a in ("renames", "breaking", "other", "layer0")
        if f'id="section-{a}"' in main
    ]
    assert 'id="section-renames"' in main
    assert main.index('id="section-renames"') == min(positions)


def test_render_breaking_section_omitted_when_no_breaking():
    out = _render("html_escaping_before.ttl", "html_escaping_after.ttl")
    assert 'id="section-breaking"' not in out


def test_render_other_changes_section_groups_non_breaking_additive_info():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert 'id="section-other"' in out
    assert "Other changes" in out


def test_render_unexplained_layer0_section_collapsed_by_default():
    out = _render("unexplained_layer0_before.ttl", "unexplained_layer0_after.ttl")
    section = _section(out, "layer0")
    assert 'data-collapsed="true"' in section
    assert 'aria-expanded="false"' in section


def test_render_sections_have_aria_expanded_initial_true():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    breaking = _section(out, "breaking")
    assert 'aria-expanded="true"' in breaking


# --------------------------------------------------------------------------- #
# Cards
# --------------------------------------------------------------------------- #


def test_render_card_has_correct_severity_class():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert 'class="change-card severity-breaking"' in out
    assert 'class="change-card severity-additive"' in out


def test_render_card_includes_stripe_div():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert '<div class="card-stripe" aria-hidden="true"></div>' in out


def test_render_card_includes_change_id_data_attribute():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert re.search(r'data-change-id="structural:[^"]+"', out)


def test_render_card_includes_kind_data_attribute():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert 'data-kind="object_property_removed"' in out


def test_render_card_details_collapsed_by_default():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    # <details> without an `open` attribute is collapsed (Q3).
    assert '<details class="card-details">' in out
    assert '<details class="card-details" open' not in out


# --------------------------------------------------------------------------- #
# Per-kind summary rendering (render_change_summary in isolation)
# --------------------------------------------------------------------------- #


def test_render_iri_uses_prefixed_form_when_known():
    # era_evolution carries changes on era:Track; the known prefix shortens it.
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    # The card-subject chip shows the prefixed form; the full IRI lives only in
    # the title attribute and the details list.
    assert ">era:Track</code>" in out


def test_render_arrow_change_uses_del_and_ins_tags():
    change = _change(
        "annotation_changed",
        severity="info",
        entity_iri="http://data.europa.eu/949/Track",
        predicate_short="label",
        language="fr",
        before={"value": "Voie", "is_iri_value": False},
        after={"value": "Voie ferrée", "is_iri_value": False},
    )
    out = render_change_summary(change, _ERA)
    assert "<del>" in out and "<ins>" in out
    assert "Voie ferrée" in out


def test_render_class_renamed_includes_confidence_evidence():
    change = _change(
        "class_renamed",
        before_iri="http://data.europa.eu/949/Track",
        after_iri="http://data.europa.eu/949/RailwayTrack",
        entity_kind="class",
        confidence="high",
        evidence=['matching label "Track"@en'],
    )
    out = render_change_summary(change, _ERA)
    assert "high confidence" in out
    assert "matching label &quot;Track&quot;@en" in out
    assert "oc-evidence" in out


def test_render_restriction_changed_includes_readable_form():
    change = _change(
        "restriction_changed",
        severity="non_breaking",
        summary="Restriction changed on era:Track: era:hasMaxSpeed max 1 → max 2",
        entity_iri="http://data.europa.eu/949/Track",
    )
    out = render_change_summary(change, _ERA)
    assert 'class="restriction"' in out
    assert "max 1 → max 2" in out


def test_render_domain_union_changed_includes_member_diff():
    out = render(_result_anon("domain_union_mixed_v1.ttl", "domain_union_mixed_v2.ttl"))
    card = _card(out, "domain_union_changed")
    assert 'class="member-add"' in card
    assert 'class="member-del"' in card
    assert "era:VehicleTypeOriginal" in card


def test_render_datatype_facet_changed_includes_facet_diff():
    change = _change(
        "datatype_facet_changed",
        severity="non_breaking",
        summary="Range facet changed on era:speed: max 327670 → 100000",
        property_iri="http://data.europa.eu/949/speed",
    )
    out = render_change_summary(change, _ERA)
    assert "327670" in out and "100000" in out


def test_render_replaced_by_set_includes_target():
    change = _change(
        "replaced_by_set",
        severity="info",
        summary="Replaced by on era:OldTrack: era:NewTrack",
        entity_iri="http://data.europa.eu/949/OldTrack",
    )
    out = render_change_summary(change, _ERA)
    assert "era:NewTrack" in out


def test_render_unknown_kind_falls_back_to_summary_text():
    change = _change("totally_unknown_kind", summary="A bespoke one-liner")
    assert render_change_summary(change, _ERA) == "<p>A bespoke one-liner</p>"


# --------------------------------------------------------------------------- #
# Escaping
# --------------------------------------------------------------------------- #


def test_render_escapes_html_in_labels():
    out = _render("html_escaping_before.ttl", "html_escaping_after.ttl")
    assert "&lt;script&gt;" in out
    assert "<script>alert" not in out  # the payload never becomes a live tag


def test_render_escapes_ampersand_in_labels():
    out = _render("html_escaping_before.ttl", "html_escaping_after.ttl")
    assert "&amp;" in out
    # The raw label (with bare &) does not appear unescaped in the body text.
    assert ' & "quoted"' not in out


def test_render_escapes_quotes_in_attributes():
    out = _render("html_escaping_before.ttl", "html_escaping_after.ttl")
    assert "&quot;quoted&quot;" in out


def test_escape_html_handles_each_special_char():
    assert escape_html("<&>\"'") == "&lt;&amp;&gt;&quot;&#x27;"
    assert escape_html("a & b") == "a &amp; b"
    assert escape_html("<x>") == "&lt;x&gt;"


# --------------------------------------------------------------------------- #
# JSON payload + footer
# --------------------------------------------------------------------------- #


def test_render_embeds_json_payload_when_option_set():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    assert '<script id="diff-json" type="application/json">' in out
    assert '"schema_version": 1' in out


def test_render_does_not_embed_json_when_option_unset():
    out = render(
        _result("era_evolution_v1.ttl", "era_evolution_v2.ttl"),
        HtmlOptions(embed_json=False),
    )
    assert 'id="diff-json"' not in out


def test_render_json_payload_neutralises_script_breakout():
    out = _render("html_escaping_before.ttl", "html_escaping_after.ttl")
    payload = out[out.index('id="diff-json"') : out.index("</script>", out.index('id="diff-json"'))]
    assert "</script>" not in payload
    assert "\\u003c" in payload  # the "<" of the embedded label is neutralised


def test_render_footer_includes_version():
    from owlcompare._version import __version__

    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert f"owlcompare</a> {__version__}" in out


def test_render_footer_includes_timestamp():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert "1970-01-01 00:00:00 UTC" in out  # SOURCE_DATE_EPOCH=0


def test_render_omits_footer_when_disabled():
    out = render(
        _result("era_evolution_v1.ttl", "era_evolution_v2.ttl"),
        HtmlOptions(include_footer=False),
    )
    assert '<footer class="report-footer">' not in out
    assert "Generated by" not in out


# --------------------------------------------------------------------------- #
# Determinism, no-inline-style, no-inline-handlers, size, theme
# --------------------------------------------------------------------------- #


def test_render_output_is_deterministic():
    result = _result("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert render(result) == render(result)


def test_render_no_inline_style_attributes():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    # No element carries a style="" attribute; all styling lives in <style>.
    assert not re.search(r"<[a-zA-Z][^>]*\sstyle=", out)


def test_render_no_javascript_event_handlers_inline():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    for handler in ("onclick=", "onload=", "onmouseover=", "onerror="):
        assert handler not in out


def test_render_toolbar_buttons_have_aria_labels():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    for label in ("Download JSON", "Copy link", "Toggle theme"):
        assert f'aria-label="{label}"' in out


def test_render_document_size_under_5mb_for_2000_changes():
    out = render(_synthetic_result(2000))
    assert len(out.encode("utf-8")) < 5 * 1024 * 1024


def test_render_default_theme_attribute_set_to_auto():
    out = _render("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert 'data-theme-default="auto"' in out
    assert 'data-theme="' not in out.split("\n")[1]  # no explicit override on <html>


def test_render_default_theme_attribute_set_to_light_when_option_light():
    out = render(
        _result("era_evolution_v1.ttl", "era_evolution_v2.ttl"),
        HtmlOptions(default_theme="light"),
    )
    assert 'data-theme-default="light"' in out
    assert 'data-theme="light"' in out


def test_render_default_theme_attribute_set_to_dark_when_option_dark():
    out = render(
        _result("era_evolution_v1.ttl", "era_evolution_v2.ttl"),
        HtmlOptions(default_theme="dark"),
    )
    assert 'data-theme="dark"' in out


# --------------------------------------------------------------------------- #
# Golden files (byte-for-byte locked contract; SOURCE_DATE_EPOCH pinned)
# --------------------------------------------------------------------------- #


def _golden(name: str) -> str:
    return (GOLDEN / name).read_text(encoding="utf-8")


def test_render_golden_empty_diff():
    out = render(_result("identical_a.ttl", "identical_b.ttl"))
    assert out == _golden("empty_diff.html")


def test_render_golden_era_evolution():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    assert out == _golden("era_evolution.html")


def test_render_golden_era_renames():
    out = render(_result("era_renames_v1.ttl", "era_renames_v2.ttl", base=RENAME))
    assert out == _golden("era_renames.html")


def test_render_golden_era_axleSpacingDistance_domain_union():
    out = render(_result_anon("domain_union_mixed_v1.ttl", "domain_union_mixed_v2.ttl"))
    assert out == _golden("era_axleSpacingDistance_domain_union.html")


def test_render_golden_breaking_only():
    out = render(_result("removed_class_before.ttl", "removed_class_after.ttl"))
    assert out == _golden("breaking_only.html")


def test_render_golden_escaping_specials():
    out = render(_result("html_escaping_before.ttl", "html_escaping_after.ttl"))
    assert out == _golden("escaping_specials.html")


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #


def _result_anon(name_a: str, name_b: str) -> DiffResult:
    a = dataclasses.replace(load(str(ANON / name_a)), source="era_axleSpacingDistance_v1.ttl")
    b = dataclasses.replace(load(str(ANON / name_b)), source="era_axleSpacingDistance_v2.ttl")
    return orchestrator.run(a, b)


def _section(html: str, anchor: str) -> str:
    start = html.index(f'id="section-{anchor}"')
    section_start = html.rindex("<section", 0, start)
    end = html.index("</section>", start)
    return html[section_start:end]


def _card(html: str, kind: str) -> str:
    match = re.search(
        rf'<article class="change-card[^>]*data-kind="{kind}".*?</article>', html, re.S
    )
    assert match, f"no card for kind {kind}"
    return match.group(0)
