"""Acceptance tests for the JUnit XML report — specs/18-junit-xml.md.

The fine-grained tests build ``Change`` objects directly so each mapping rule and
escaping path is pinned in isolation; the ``test_render_golden_*`` tests assert
byte-for-byte equality against ``tests/fixtures/junit/*.xml`` (generated by the
renderer, then hand-reviewed). ``SOURCE_DATE_EPOCH`` is pinned module-wide so the
``timestamp`` attribute is stable.
"""

from __future__ import annotations

import dataclasses
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest

from owlcompare.diff import orchestrator
from owlcompare.diff._common import Change, DiffResult
from owlcompare.loader import load
from owlcompare.report.junit_report import JUnitOptions, render

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures"
DIFF = FIXTURES / "diff"
RENAME = FIXTURES / "rename"
GOLDEN = FIXTURES / "junit"

_ERA = {"era": "http://data.europa.eu/949/"}


@pytest.fixture(autouse=True)
def _pin_timestamp(monkeypatch: pytest.MonkeyPatch) -> None:
    """Pin SOURCE_DATE_EPOCH so every render in this module is deterministic."""
    monkeypatch.setenv("SOURCE_DATE_EPOCH", "0")


# --------------------------------------------------------------------------- #
# Result / change builders
# --------------------------------------------------------------------------- #


def _result(name_a: str, name_b: str, base: Path = DIFF, **run_kwargs: object) -> DiffResult:
    a = dataclasses.replace(load(str(base / name_a)), source=name_a)
    b = dataclasses.replace(load(str(base / name_b)), source=name_b)
    return orchestrator.run(a, b, **run_kwargs)  # type: ignore[arg-type]


def _change(kind: str, severity: str = "additive", summary: str = "", **details: object) -> Change:
    return Change(
        layer="structural",
        kind=kind,
        severity=severity,  # type: ignore[arg-type]
        subject=str(details.get("entity_iri") or details.get("before_iri") or "") or None,
        summary=summary,
        details=details,
    )


def _synthetic_result(changes: tuple[Change, ...]) -> DiffResult:
    """A DiffResult with hand-built changes and no orchestrator metadata."""
    snapshot = dataclasses.replace(load(str(DIFF / "identical_a.ttl")), source="a.ttl")
    snapshot_b = dataclasses.replace(snapshot, source="b.ttl")
    return DiffResult(a=snapshot, b=snapshot_b, changes=changes, metadata={})


# --------------------------------------------------------------------------- #
# Document skeleton
# --------------------------------------------------------------------------- #


def test_render_returns_valid_xml_declaration():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    assert out.startswith('<?xml version="1.0" encoding="UTF-8"?>\n')


def test_render_includes_testsuites_root_element():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    assert '<testsuites name="owlcompare"' in out
    assert out.rstrip().endswith("</testsuites>")


def test_render_includes_testsuite_with_name():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    assert '<testsuite name="owlcompare.diff"' in out


def test_render_counts_total_tests_correctly():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    root = ET.fromstring(out)
    assert root.get("tests") == "5"
    assert root.find("testsuite").get("tests") == "5"


def test_render_counts_failures_correctly():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    root = ET.fromstring(out)
    assert root.get("failures") == "1"  # only object_property_removed is breaking


def test_render_counts_skipped_correctly():
    out = render(
        _result("era_evolution_v1.ttl", "era_evolution_v2.ttl"),
        JUnitOptions(include_skipped=True),
    )
    root = ET.fromstring(out)
    assert root.get("skipped") == "2"  # the label change + the ontology metadata change


# --------------------------------------------------------------------------- #
# Severity → result mapping
# --------------------------------------------------------------------------- #


def test_render_breaking_change_emits_failure_element():
    change = _change("class_removed", severity="breaking", summary="Class removed", entity_iri="x")
    out = render(_synthetic_result((change,)))
    assert "<failure" in out


def test_render_non_breaking_change_no_failure():
    change = _change("restriction_changed", severity="non_breaking", summary="R", entity_iri="x")
    out = render(_synthetic_result((change,)))
    assert "<failure" not in out
    assert "<skipped" not in out


def test_render_additive_change_no_failure():
    change = _change("class_added", severity="additive", summary="C", entity_iri="x")
    out = render(_synthetic_result((change,)))
    assert "<failure" not in out


def test_render_info_change_passes_by_default():
    change = _change("annotation_changed", severity="info", summary="L", entity_iri="x")
    out = render(_synthetic_result((change,)))
    assert "<skipped" not in out
    assert "<failure" not in out


def test_render_info_change_skipped_when_flag_enabled():
    change = _change("annotation_changed", severity="info", summary="L", entity_iri="x")
    out = render(_synthetic_result((change,)), JUnitOptions(include_skipped=True))
    assert "<skipped" in out


def test_render_rename_change_passes():
    # A rename carries info severity, but renames always pass — even with the flag.
    change = _change(
        "class_renamed",
        severity="info",
        summary="Class renamed",
        before_iri="http://data.europa.eu/949/Track",
        after_iri="http://data.europa.eu/949/RailwayTrack",
        entity_kind="class",
    )
    out = render(_synthetic_result((change,)), JUnitOptions(include_skipped=True))
    assert "<skipped" not in out
    assert "<failure" not in out


# --------------------------------------------------------------------------- #
# Testcase classname + name
# --------------------------------------------------------------------------- #


def test_render_testcase_classname_format():
    change = _change("class_added", severity="additive", summary="C", entity_iri="x")
    out = render(_synthetic_result((change,)))
    assert 'classname="structural.class_added"' in out


def test_render_testcase_name_uses_subject_when_available():
    change = _change("class_added", entity_iri="http://data.europa.eu/949/Platform")
    a = dataclasses.replace(load(str(DIFF / "identical_a.ttl")), source="a.ttl", prefixes=_ERA)
    result = DiffResult(a=a, b=a, changes=(change,), metadata={})
    out = render(result)
    assert 'name="era:Platform"' in out


def test_render_testcase_name_truncates_long_iris():
    long_iri = "http://example.org/" + "x" * 200
    change = _change("class_added", entity_iri=long_iri)
    out = render(_synthetic_result((change,)))
    root = ET.fromstring(out)
    name = root.find(".//testcase").get("name")
    assert len(name) == 60
    assert name.endswith("...")


# --------------------------------------------------------------------------- #
# Failure element content
# --------------------------------------------------------------------------- #


def test_render_failure_type_is_kind():
    change = _change("object_property_removed", severity="breaking", summary="X", entity_iri="x")
    out = render(_synthetic_result((change,)))
    assert '<failure type="object_property_removed"' in out


def test_render_failure_message_is_summary():
    change = _change(
        "class_removed", severity="breaking", summary="Class removed: era:Foo", entity_iri="x"
    )
    out = render(_synthetic_result((change,)))
    assert 'message="Class removed: era:Foo"' in out


def test_render_failure_body_includes_iri_and_details():
    change = _change(
        "class_removed",
        severity="breaking",
        summary="Class removed",
        entity_iri="http://example.org/Cat",
        label="Cat",
        language="en",
    )
    out = render(_synthetic_result((change,)))
    root = ET.fromstring(out)
    body = root.find(".//failure").text
    assert "Entity:    http://example.org/Cat" in body  # the full IRI, not the prefixed form
    assert "Kind:      class_removed" in body
    assert '"Cat"@en' in body
    assert "Severity:  breaking" in body


def test_render_failure_body_includes_subsumes_when_present():
    change = _change(
        "class_removed",
        severity="breaking",
        summary="Class removed",
        entity_iri="http://example.org/Cat",
        subsumes=["syntactic:triple_removed:aaa", "syntactic:triple_removed:bbb"],
    )
    out = render(_synthetic_result((change,)))
    body = ET.fromstring(out).find(".//failure").text
    assert "Subsumed Layer 0 changes:" in body
    assert "syntactic:triple_removed:aaa" in body
    assert "syntactic:triple_removed:bbb" in body


def test_render_breaking_change_without_summary_uses_fallback_message():
    change = _change("class_removed", severity="breaking", summary="", entity_iri="x")
    out = render(_synthetic_result((change,)))
    assert 'message="breaking change of kind class_removed"' in out


# --------------------------------------------------------------------------- #
# <system-out>
# --------------------------------------------------------------------------- #


def test_render_system_out_when_enabled():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    assert "<system-out><![CDATA[" in out
    assert "]]></system-out>" in out


def test_render_system_out_contains_text_rendering():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    assert "owlcompare diff" in out
    assert "Layer 1 — Structural" in out


def test_render_system_out_omitted_when_disabled():
    out = render(
        _result("era_evolution_v1.ttl", "era_evolution_v2.ttl"),
        JUnitOptions(include_system_out=False),
    )
    assert "<system-out>" not in out


def test_render_system_out_escapes_cdata_terminator():
    # A label smuggling a "]]>" must not terminate the CDATA section early.
    change = _change(
        "class_added",
        severity="additive",
        summary="Class added: evil ]]> escape attempt",
        entity_iri="http://example.org/Evil",
    )
    out = render(_synthetic_result((change,)))
    # The split-CDATA escape is applied (the lone "]]>" within it is the legitimate
    # terminator of the first chunk; a fresh CDATA reopens for the trailing ">")...
    assert "]]]]><![CDATA[>" in out
    # ...and the document still parses, recovering the original three characters.
    text = ET.fromstring(out).find(".//system-out").text
    assert "evil ]]> escape attempt" in text


# --------------------------------------------------------------------------- #
# Suite name resolution
# --------------------------------------------------------------------------- #


def test_render_suite_name_default():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    assert '<testsuite name="owlcompare.diff"' in out


def test_render_suite_name_override():
    out = render(
        _result("era_evolution_v1.ttl", "era_evolution_v2.ttl"),
        JUnitOptions(suite_name="My Ontology Diff"),
    )
    assert '<testsuite name="My Ontology Diff"' in out


# --------------------------------------------------------------------------- #
# XML escaping
# --------------------------------------------------------------------------- #


def test_render_xml_escapes_special_chars_in_labels():
    change = _change(
        "class_removed",
        severity="breaking",
        summary="Class removed",
        entity_iri="http://example.org/X",
        label="<script>alert('x')</script>",
        language="en",
    )
    out = render(_synthetic_result((change,)))
    # The failure body is element text: < and > become entities, no live tag.
    assert "&lt;script&gt;" in out
    assert "<script>alert" not in out


def test_render_xml_escapes_quotes_in_attributes():
    change = _change(
        "class_removed",
        severity="breaking",
        summary='Class removed: "Quoted" name',
        entity_iri="http://example.org/X",
    )
    out = render(_synthetic_result((change,)))
    # The summary is the failure message attribute; its quotes must be escaped.
    assert 'message="Class removed: &quot;Quoted&quot; name"' in out


def test_render_xml_escapes_ampersand_in_iris():
    change = _change(
        "class_removed",
        severity="breaking",
        summary="Class removed",
        entity_iri="http://example.org/A&B",
    )
    out = render(_synthetic_result((change,)))
    body = ET.fromstring(out).find(".//failure").text  # parses only if & is escaped
    assert "http://example.org/A&B" in body


# --------------------------------------------------------------------------- #
# Determinism + ordering
# --------------------------------------------------------------------------- #


def test_render_testcases_sorted_by_classname_then_name():
    changes = (
        _change("class_added", entity_iri="http://example.org/Zebra"),
        _change("class_added", entity_iri="http://example.org/Apple"),
        _change("annotation_changed", severity="info", summary="A", entity_iri="http://e/Z"),
    )
    out = render(_synthetic_result(changes))
    root = ET.fromstring(out)
    keys = [(tc.get("classname"), tc.get("name")) for tc in root.findall(".//testcase")]
    assert keys == sorted(keys)


def test_render_timestamp_honors_source_date_epoch():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    assert 'timestamp="1970-01-01T00:00:00"' in out


def test_render_timestamp_override_takes_priority(monkeypatch):
    out = render(
        _result("era_evolution_v1.ttl", "era_evolution_v2.ttl"),
        JUnitOptions(timestamp="2026-06-06T12:00:00"),
    )
    assert 'timestamp="2026-06-06T12:00:00"' in out


def test_render_output_is_deterministic():
    result = _result("era_evolution_v1.ttl", "era_evolution_v2.ttl")
    assert render(result) == render(result)


# --------------------------------------------------------------------------- #
# Edge cases
# --------------------------------------------------------------------------- #


def test_render_empty_diff_emits_no_changes_testcase():
    out = render(_result("identical_a.ttl", "identical_b.ttl"))
    root = ET.fromstring(out)
    cases = root.findall(".//testcase")
    assert len(cases) == 1
    assert cases[0].get("name") == "no-changes"
    assert root.get("tests") == "1"


def test_render_change_without_subject_uses_summary_as_name():
    change = Change(
        layer="syntactic",
        kind="triple_removed",
        severity="info",
        subject=None,
        summary="some bare triple summary",
        details={},
    )
    out = render(_synthetic_result((change,)))
    assert 'name="some bare triple summary"' in out


def test_render_xml_validates_against_jenkins_schema():
    # Basic well-formedness: ElementTree.parse must accept the document.
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    ET.fromstring(out)  # raises ParseError on malformed XML


# --------------------------------------------------------------------------- #
# Golden files (byte-for-byte locked contract; SOURCE_DATE_EPOCH pinned)
# --------------------------------------------------------------------------- #


def _golden(name: str) -> str:
    return (GOLDEN / name).read_text(encoding="utf-8")


def test_render_golden_empty():
    out = render(_result("identical_a.ttl", "identical_b.ttl"))
    assert out == _golden("empty.xml")


def test_render_golden_era_evolution():
    out = render(_result("era_evolution_v1.ttl", "era_evolution_v2.ttl"))
    assert out == _golden("era_evolution.xml")


def test_render_golden_era_renames():
    out = render(_result("era_renames_v1.ttl", "era_renames_v2.ttl", RENAME))
    assert out == _golden("era_renames.xml")


def test_render_golden_breaking_only():
    out = render(_result("removed_class_before.ttl", "removed_class_after.ttl"))
    assert out == _golden("breaking_only.xml")


def test_render_golden_non_breaking_only():
    out = render(_result("widened_range_before.ttl", "widened_range_after.ttl"))
    assert out == _golden("non_breaking_only.xml")


def test_render_golden_escaping_specials():
    out = render(_result("html_escaping_before.ttl", "html_escaping_after.ttl"))
    assert out == _golden("escaping_specials.xml")


def test_render_golden_with_info_skipped():
    out = render(
        _result("era_evolution_v1.ttl", "era_evolution_v2.ttl"),
        JUnitOptions(include_skipped=True),
    )
    assert out == _golden("with_info_skipped.xml")
